version: '3'
services:
    app:
        command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 dist/api/app.js
        depends_on:
            - mysql
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
    mysql:
        image: mysql:8.0.1
        restart: always
        volumes:
            - ./.db:/var/lib/mysql
        ports:
            - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cheil
        logging:
            driver: none
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/opt/html
        ports:
            - 80:80
        logging:
            driver: none
